changed /MD to /MT flag in pthread.lib project
without this change it will cause following error:

```
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>pthread_lib.lib(create.obj) : error LNK2001: unresolved external symbol __imp__beginthreadex
1>pthread_lib.lib(ptw32_threadStart.obj) : error LNK2001: unresolved external symbol __imp__endthreadex
1>pthread_lib.lib(pthread_win32_attach_detach_np.obj) : error LNK2001: unresolved external symbol __imp_wcsncat_s
1>fatal error LNK1120: 3 unresolved externals```

when linking pthread_lib.lib with release project compiled with /MT flag.

More information available here: https://stackoverflow.com/questions/3007312/resolving-lnk4098-defaultlib-msvcrt-conflicts-with